### PR TITLE
Fix bug when multiple tags and digest path present

### PR DESCRIPTION
**Pull request by johnboyes**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

When providing both multiple tags and a digest path in `docker/push`,
the digest lookup would previously fail with `invalid reference format`
as it would append all the tags. 

[Here is an example of this bug](https://app.circleci.com/pipelines/github/agilepathway/cimg-gauge/109/workflows/a8534681-9984-4de8-8711-6c446bf1ec96/jobs/294) manifesting itself, caused by having [both multiple tags and a digest path specified](https://github.com/agilepathway/cimg-gauge/commit/6de0a4bcea736f8347ea9b01bec2b42b1ff66882), e.g:

```
- docker/push:
    digest-path: /tmp/digest
    image: agilepathway/cimg-gauge-multiple-tags
    tag: 'tag1,tag2'
```

### Description

Fix bug in `docker/push` command when specifying both of the following together:

1. multiple tags
2. digest path

Fix by now always using the first provided tag for the digest lookup.

### Testing

I manually tested the following scenarios by [forking](https://github.com/agilepathway/docker-orb) the Docker Orb, [deploying the fix](https://app.circleci.com/pipelines/github/agilepathway/docker-orb/29/workflows/3090a22b-3ffb-4a86-b4ce-7f579e1b8f48) and then testing against it:

1. [Multiple tags with digest path](https://app.circleci.com/pipelines/github/agilepathway/cimg-gauge/116/workflows/986a27c8-79a3-4e2d-9185-e29cbc20209b/jobs/303)
2. [Single tag with digest path](https://app.circleci.com/pipelines/github/agilepathway/cimg-gauge/114/workflows/9f63e9eb-57d7-44fe-90c9-4e5ff14d18f9/jobs/301)
3. [Default tag (i.e. no tag parameter) with digest path](https://app.circleci.com/pipelines/github/agilepathway/cimg-gauge/117/workflows/3e09c2b4-9772-4323-9779-08b8ebe8ce8e/jobs/304)

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hello @johnboyes,

It looks like you are creating an array from the two tags and selecting the first one, is that right? What is the reason someone might push two tags at once? And if they try,, should we provide better erroring rather than assuming the first tag?

**Comment by johnboyes** [comment]
Hi @KyleTryon, thanks for the comment.

> What is the reason someone might push two tags at once?

Because that is the current documented functionality:

https://circleci.com/orbs/registry/orb/circleci/docker#commands-push

> Comma-separated list of image tag, defaults to the value of $CIRCLE_SHA1

An obvious example would be specifying multiple tags for the [publish](https://circleci.com/orbs/registry/orb/circleci/docker#jobs-publish) job, again as per the documentation.  The job currently passes the comma separated list of tags on to the push command, which will blow up if a digest path is provided too.

It's normal in Docker to have multiple tags when pushing an image (and should be encouraged, in my opinion, as e.g. tagging versions of installed software on the image is good practice).

The default behaviour of `docker push` is to [push all tags](https://stackoverflow.com/a/56905333) if a tag is not specified.

> It looks like you are creating an array from the two tags

Yes, that's right, in exactly the same way that [the orb's push command already does](https://github.com/CircleCI-Public/docker-orb/blob/7eb318e41e4dc23eb71588ab9f762568078a569a/src/commands/push.yml#L33-L36).

> should we provide better erroring rather than assuming the first tag?

All the tags passed in via the `tag` parameter are being tagged on the *same pushed docker image*, so we can use any of them safely to take the digest from (as the digest is of course the same).  As we have to take one tag to obtain the digest from, the [principle of least surprise](https://wiki.c2.com/?PrincipleOfLeastAstonishment) is to take the first one.

**Comment by johnboyes** [comment]
Hi @KyleTryon, very grateful if you can have a look at my reply when you have a chance, pls :-)

**Comment by KyleTryon** [comment]
All excellent points, thank you for the explanation @johnboyes, and apologies for the delay. Merging this now as a patch release.

**Comment by gmemstr** [comment]
Looks good to me as well, there's been a few minor releases for the Orb so this will land as 1.2.1.

**Pull request merged**
