### PR TITLE
feat: add buildkit support

### LINKED ISSUE #83: BuildKit support
I don't see BuildKit support documented anywhere, but it should be supported in docker 18.09+.

### PR DESCRIPTION
**Pull request by EricRibeiro**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

Closes #83 

### Description
Add a new BuildKit parameter to the `build` command and `publish` job. 

BuildKit is only available on Docker >= 18.03, and since CircleCI [defaults](https://circleci.com/docs/2.0/building-docker-images/#docker-version) to v17.09, it was necessary to add a parameter to change the remote Docker version.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:04578ca9d877daee0b276db78862d59fd28510da

**Review by brivu — APPROVED** [review]
Looks good!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:87c3dfc05b5571e2566db25a37b8c21ca74884a7

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:87c3dfc05b5571e2566db25a37b8c21ca74884a7

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=2.1.0

**Pull request merged**
