### PR TITLE
Expand ENV vars in `cache_from` parameter

### PR DESCRIPTION
**Pull request by jgarber623**
Resolves CircleCI-Public/docker-orb#166.

### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

As noted above, this PR resolves CircleCI-Public/docker-orb#166.

### Description

This change _should_ correctly expand ENV variables set in the `cache_from` build parameter. I used a similar approach to the one used in CircleCI-Public/docker-orb#149.

### CODE REVIEW

**Comment by EricRibeiro** [comment]
Hi @jgarber623 👋 ,

Thank you for proactively fixing an issue you encountered. Instead of focusing on one parameter or the other, I opted to create a function that expands all of them in #171.

I'll release a new version with the changes shortly.

**Comment by jgarber623** [comment]
@EricRibeiro #171 looks great! Thank you for putting that together. 🙌🏻 

I'll keep an eye out for the updated relase.

**Comment by EricRibeiro** [comment]
> @EricRibeiro #171 looks great! Thank you for putting that together. 🙌🏻
> 
> I'll keep an eye out for the updated relase.

Thanks for understanding. You can check it out on [v2.1.5](https://circleci.com/developer/orbs/orb/circleci/docker?version=2.1.5).

Let me know how it goes 😁

**Comment by jgarber623** [comment]
> Let me know how it goes 😁

@EricRibeiro Had a chance to test v2.1.5 and everything works as intended. 🎉 

Moved to using a command config similar to (reproduced from #166):

```yaml
- docker/build:
    cache_from: us.gcr.io/${GOOGLE_PROJECT_ID}/xxxx:${CIRCLE_BRANCH}-${CIRCLE_SHA1},us.gcr.io/${GOOGLE_PROJECT_ID}/xxxx:${CIRCLE_BRANCH}-latest
    registry: us.gcr.io
    tag: ${CIRCLE_BRANCH}-${CIRCLE_SHA1},${CIRCLE_BRANCH}-latest
    use-buildkit: true
```

Thanks again for your help!

**Pull request closed without merging**
