### PR TITLE
Support multi-arch environments

### PR DESCRIPTION
**Pull request by n-029894**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

The current build only supports x86_64 architectures.

### Description

This installs the docker version which is appropriate to the environment in which it is being executed on.

### CODE REVIEW

**Comment by KyleTryon** [comment]
Hey @n-029894 thanks for the PR! It looks good but we'll need to get some tests added before we merge. Would you be willing to add and arm executor to the list of executors here: https://github.com/CircleCI-Public/docker-orb/blob/06d0cd8c222a96086cbbe7ae70f5500c9b22f741/.circleci/test-deploy.yml#L618

and then add that to the matrix lists in the appropriate tests above. 

If we have write access to the fork we can contribute that as well

**Comment by n-029894** [comment]
@KyleTryon I updated places where the tests were not defined. I believe the arm executor is already there though.

https://github.com/n-029894/docker-orb/blob/master/.circleci/test-deploy.yml#L640-L643

Please let me know if I am missing anything else. Thanks.

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:1e4ebe82d4f3c31ded7b9f3f43c6a860051da5e3

**Comment by EricRibeiro** [comment]
Thanks for the changes @n-029894!

The tests are failing in the Dockerize installation due to [this](https://github.com/CircleCI-Public/docker-orb/pull/185/commits/d0410ed05860748a9757dd53405ed5ae0159bb2c#diff-2c7756a40669c839affabc4cab649e0c8ee5a0e6ec5330555900fde94bb224caL36) change.

`uname -m` returns `x86_64` but Dockerize does not name its releases in such way. Hence the 404 error. Would you mind looking into it?

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:e991aee15d84a84d4ffcecc7f562fcb14d81fdbc

**Comment by EricRibeiro** [comment]
Thanks!

Arm Linux Medium executor returns `aarch64` under `uname -m`.

**Comment by n-029894** [comment]
🤞

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:9b086d959d5a56e4cb8e32a55bed30b9b6051d63

**Review by EricRibeiro — APPROVED** [review]
Thank you! 🙇

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:98779bcb3ea84c300a441b8ca861e6adb8a855ce

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:98779bcb3ea84c300a441b8ca861e6adb8a855ce

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=2.4.0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:98779bcb3ea84c300a441b8ca861e6adb8a855ce

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:98779bcb3ea84c300a441b8ca861e6adb8a855ce

**Pull request merged**
