### PR TITLE
refactor: extract scripts from pull, push and update-descriptions

### PR DESCRIPTION
**Pull request by EricRibeiro**
### Checklist

- [x] All new jobs, commands, executors, parameters have descriptions
- [x] Examples have been added for any significant new features
- [x] README has been updated, if necessary

### Motivation, issues

This change will bring the orb closer to best practices and allow for more straightforward implementation of features, maintenance and troubleshooting.

### Description

All bash scripting was moved from the yaml to a `.sh` file.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:29fad60744234fe2503a352595f3ad367c40d1f3

**Review by KyleTryon — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:1ee8909f75b2c30fb19a8cc470de7ca5c601b8bd

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:42998e2afc4c280e4521021d94ab9dcf96753a64

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:031f7bf00be3113d34d5499e492faf27c37af9d5

**Pull request merged**
