### PR TITLE
Change test context

### PR DESCRIPTION
**Pull request by joshhsoj1902**
### Description

Updating which cci contexts are used in tests

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:b57bc7bb3446ceef0178150e2c327c4c9df06400

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:fd1856584fc6984ca4496711db26e7112975c752

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:d791320d8f6150b63b5b16019f233ef131149333

**Review by bjohnso5 — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:2542b283c4d6a1c343b71b8d47d0f2d470eb2e49

**Pull request merged**
