### PR TITLE
feat: update default image to support arm resource class

### PR DESCRIPTION
**Pull request by brivu**
This `PR` updates the default image for the `machine` executor to support `arm64` it also adds the `resource-class` parameter to the executor as well.

### CODE REVIEW

**Review by EricRibeiro — APPROVED** [review]

**Comment by KyleTryon** [comment]
This change might have changed the version of Docker-compose. This test will need to be updated: https://app.circleci.com/pipelines/github/CircleCI-Public/docker-orb/980/workflows/fb166b7e-ca46-4333-9d8b-cea155694198/jobs/19829

**Review by KyleTryon — CHANGES_REQUESTED** [review]
This change might have changed the version of Docker-compose. This test will need to be updated: https://app.circleci.com/pipelines/github/CircleCI-Public/docker-orb/980/workflows/fb166b7e-ca46-4333-9d8b-cea155694198/jobs/19829

**Comment by brivu** [comment]
@KyleTryon - I just ran the tests again and it looks like it worked.

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:5b8b43e685aab2afbf27ea2b0c2e3b9a447e3c61

**Review by KyleTryon — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/docker?version=dev:dcb1c8c287afa50d9672fe794943bdf732e8c1c2

**Pull request merged**
